[tool.poetry]
name = "pyqtgraph_extensions"
version = "0.5.0"
description = "Various extensions for pyqtgraph."
authors = ["Dane Austin <dane_austin@fastmail.com.au>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.6"
pyqtgraph = {git = "https://github.com/pyqtgraph/pyqtgraph.git"}
PyQt5 = "^5.14.2"
mathx = "^0.2.0"
pyopengl = "^3.1.5"

[tool.poetry.dev-dependencies]
pytest = "^5.4.2"
pytest-qt = "^3.3.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
